/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifrn.view;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author eaudevie
 */
public class TelaAtualizar extends javax.swing.JDialog {

	/**
     * Creates new form TelaAtualizar
     */
	public TelaAtualizar(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		this.setLocationRelativeTo(null); //Fixar tela no meio ao abrir.
		setResizable(false); //Função para não permitir o rendimensionamento da tela.
		importarDados(); //Importando os dados do arquivo no exato momento que a tela é aberta.
		ordenarTabela(); //Em seguida ordenando (OPC).
	}

	public void importarDados() {
		String filePath = "C:\\Users\\Eau de Vie\\Desktop\\Projeto - Sistema Salão 1.1\\SistemaSalao\\dist\\logServicos.txt";
		File file = new File(filePath);

		try {
			FileReader fr = new FileReader(file);
			BufferedReader br = new BufferedReader(fr);

			DefaultTableModel model = (DefaultTableModel) tabelaservicos.getModel();

			// Pegando as linhas do arquivo TXT
			Object[] lines = br.lines().toArray();

			// Extraindo os dados do arquivo
			// Setando os dados na Jtable
			for (int i = 0; i < lines.length; i++) {

				String line = lines[i].toString().trim();
				String[] dataRow = line.split(",");
				model.addRow(dataRow);

			}

		} catch(Exception ex) {
			ex.getMessage();
		}
	}

	public void exportarDados() {
		String filePath = "C:\\Users\\Eau de Vie\\Desktop\\Projeto - Sistema Salão 1.1\\SistemaSalao\\dist\\logServicos.txt";
		File file = new File(filePath);
		try {
			FileWriter fw = new FileWriter(file);
			BufferedWriter bw = new BufferedWriter(fw);

			for (int i = 0; i < tabelaservicos.getRowCount(); i++) { //Linhas
				for (int j = 0; j < tabelaservicos.getColumnCount(); j++) { //Colunas
					bw.write(tabelaservicos.getValueAt(i, j).toString() + ",");
				}
				bw.newLine();
			}

			bw.close();
			fw.close();

		} catch(IOException ex) {
			ex.getMessage();
		}
	}

	public void ordenarTabela() {
		TableRowSorter < TableModel > sorter = new TableRowSorter < TableModel > (tabelaservicos.getModel());
		tabelaservicos.setRowSorter(sorter);
		ArrayList < RowSorter.SortKey > sortKeys = new ArrayList < RowSorter.SortKey > ();

		int indiceColuna = 7;
		sortKeys.add(new RowSorter.SortKey(indiceColuna, SortOrder.ASCENDING));

		sorter.setSortKeys(sortKeys);
		sorter.sort();
	}

	//Função utilitária que cadastra os valores modificados na jtable.
	public void cadastrarValores() {

		int linhaSelecionada = tabelaservicos.getSelectedRow();

		DefaultTableModel model = (DefaultTableModel) tabelaservicos.getModel();

		if (linhaSelecionada >= 0) {
			float preco = Float.parseFloat(txtfieldvalor.getText());
			float desconto = Float.parseFloat(txtfielddesconto.getText());

			float valorFinal = (preco - desconto);

			model.setValueAt(txtfieldcontato.getText(), linhaSelecionada, 2);
			model.setValueAt(txtfieldendereco.getText(), linhaSelecionada, 3);
			model.setValueAt(preco, linhaSelecionada, 5);
			model.setValueAt(desconto, linhaSelecionada, 6);
			model.setValueAt(txtfielddia.getText(), linhaSelecionada, 7);
			model.setValueAt(txtfieldhora.getText(), linhaSelecionada, 8);
			model.setValueAt(valorFinal, linhaSelecionada, 9);

			JOptionPane.showMessageDialog(null, "Contato atualizado com sucesso!");

		} else {
			JOptionPane.showMessageDialog(null, "Não há serviços selecionados, selecione o serviço que deseja atualizar!", "Atualizar", JOptionPane.ERROR_MESSAGE);
		}

	}

	public void limparCampos() {
		txtfieldnome.setText("");
		txtfieldcontato.setText("");
		txtfieldendereco.setText("");
		txtfieldvalor.setText("");
		txtfielddesconto.setText("");
		txtfielddia.setText("");
		txtfieldhora.setText("");
		txtfieldid.setText("");
		txtfieldservico.setText("");
		txtfieldfinal.setText("");
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tabelaservicos = new javax.swing.JTable();
		jButton4 = new javax.swing.JButton();
		btnatualizar = new javax.swing.JButton();
		jSeparator2 = new javax.swing.JSeparator();
		jLabel2 = new javax.swing.JLabel();
		txtfieldnome = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		txtfieldendereco = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		txtfieldservico = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		txtfieldvalor = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		txtfielddesconto = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		txtfieldid = new javax.swing.JTextField();
		jLabel12 = new javax.swing.JLabel();
		txtfieldfinal = new javax.swing.JTextField();
		jLabel11 = new javax.swing.JLabel();
		txtfieldhora = new javax.swing.JTextField();
		try {
			javax.swing.text.MaskFormatter hora = new javax.swing.text.MaskFormatter("##:##");

			txtfieldhora = new javax.swing.JFormattedTextField(hora);
		} catch(Exception e) {}
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		jLabel20 = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		txtfielddia = new javax.swing.JTextField();
		try {
			javax.swing.text.MaskFormatter dia = new javax.swing.text.MaskFormatter("##/##/####");

			txtfielddia = new javax.swing.JFormattedTextField(dia);
		} catch(Exception e) {}
		txtfieldcontato = new javax.swing.JTextField();
		try {
			javax.swing.text.MaskFormatter contato = new javax.swing.text.MaskFormatter("(##)#####-####");

			txtfieldcontato = new javax.swing.JFormattedTextField(contato);
		} catch(Exception e) {}
		jLabel21 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Atualizar Serviço");

		jPanel2.setBackground(java.awt.Color.darkGray);
		jPanel2.setForeground(java.awt.Color.darkGray);
		jPanel2.setName(""); // NOI18N
		tabelaservicos.setBackground(java.awt.Color.darkGray);
		tabelaservicos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		tabelaservicos.setForeground(new java.awt.Color(255, 255, 255));
		tabelaservicos.setModel(new javax.swing.table.DefaultTableModel(
		new Object[][] {

},
		new String[] {
			"ID",
			"Nome do Cliente",
			"Contato",
			"Endereço",
			"Serviço",
			"Valor/Preço",
			"Desconto",
			"Dia",
			"Hora",
			"Valor Final"
		}) {
			boolean[] canEdit = new boolean[] {
				false,
				false,
				false,
				false,
				false,
				false,
				false,
				false,
				false,
				false
			};

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		tabelaservicos.getTableHeader().setResizingAllowed(false);
		tabelaservicos.getTableHeader().setReorderingAllowed(false);
		tabelaservicos.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tabelaservicosMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(tabelaservicos);

		jButton4.setBackground(java.awt.Color.darkGray);
		jButton4.setForeground(new java.awt.Color(255, 255, 255));
		jButton4.setText("Fechar Tela");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		btnatualizar.setBackground(java.awt.Color.darkGray);
		btnatualizar.setForeground(new java.awt.Color(255, 255, 255));
		btnatualizar.setText("Atualizar Dados");
		btnatualizar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnatualizarActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("Nome");

		txtfieldnome.setEditable(false);
		txtfieldnome.setBackground(java.awt.Color.darkGray);
		txtfieldnome.setForeground(new java.awt.Color(255, 255, 255));

		jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("Contato");

		jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setText("Endereço");

		txtfieldendereco.setBackground(java.awt.Color.darkGray);
		txtfieldendereco.setForeground(new java.awt.Color(255, 255, 255));

		jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setText("Serviço");

		txtfieldservico.setEditable(false);
		txtfieldservico.setBackground(java.awt.Color.darkGray);
		txtfieldservico.setForeground(new java.awt.Color(255, 255, 255));
		txtfieldservico.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				txtfieldservicoMouseClicked(evt);
			}
		});

		jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6.setText("Preço");

		txtfieldvalor.setBackground(java.awt.Color.darkGray);
		txtfieldvalor.setForeground(new java.awt.Color(255, 255, 255));

		jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
		jLabel7.setForeground(new java.awt.Color(255, 255, 255));
		jLabel7.setText("Desconto");

		txtfielddesconto.setBackground(java.awt.Color.darkGray);
		txtfielddesconto.setForeground(new java.awt.Color(255, 255, 255));

		jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
		jLabel8.setForeground(new java.awt.Color(255, 255, 255));
		jLabel8.setText("Dia");

		jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
		jLabel9.setForeground(new java.awt.Color(255, 255, 255));
		jLabel9.setText("Hora");

		jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
		jLabel10.setForeground(new java.awt.Color(255, 255, 255));
		jLabel10.setText("ID");

		txtfieldid.setEditable(false);
		txtfieldid.setBackground(java.awt.Color.darkGray);
		txtfieldid.setForeground(new java.awt.Color(255, 255, 255));

		jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
		jLabel12.setForeground(new java.awt.Color(255, 255, 255));
		jLabel12.setText("Valor Final");

		txtfieldfinal.setEditable(false);
		txtfieldfinal.setBackground(java.awt.Color.darkGray);
		txtfieldfinal.setForeground(new java.awt.Color(255, 255, 255));

		jLabel11.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
		jLabel11.setForeground(new java.awt.Color(255, 0, 0));
		jLabel11.setText("Atenção: Selecione o campo que deseja atualizar e em seguida substitua o valor pelo desejado.");

		txtfieldhora.setBackground(java.awt.Color.darkGray);
		txtfieldhora.setForeground(new java.awt.Color(255, 255, 255));

		jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
		jLabel13.setForeground(new java.awt.Color(255, 255, 255));
		jLabel13.setText("Atualizar Serviços");

		jLabel14.setForeground(new java.awt.Color(255, 255, 255));
		jLabel14.setText("Bem Vindo, para atualizar um determinado serviço siga os passos abaixo:");

		jLabel15.setForeground(new java.awt.Color(255, 255, 255));
		jLabel15.setText("1 - Selecione na Tabela o serviço que você deseja atualizar.");

		jLabel16.setForeground(new java.awt.Color(255, 255, 255));
		jLabel16.setText("2 - Após o serviço estar selecionado, escolha nos campos de texto qual");

		jLabel17.setForeground(new java.awt.Color(255, 255, 255));
		jLabel17.setText("elemento será modificado.");

		jLabel18.setForeground(new java.awt.Color(255, 255, 255));
		jLabel18.setText("3 - Após modificar o elemento desejado, clique no botão \"Atualizar Dados\".");

		jLabel19.setForeground(new java.awt.Color(255, 255, 255));
		jLabel19.setText("OBS: Somente \"Contato\", \"Endereço\", \"Serviço\", \"Valor\", \"Desconto\", \"Dia\"");

		jLabel20.setForeground(new java.awt.Color(255, 255, 255));
		jLabel20.setText("e \"Hora\" podem ser atualizados.");

		txtfielddia.setBackground(java.awt.Color.darkGray);
		txtfielddia.setForeground(new java.awt.Color(255, 255, 255));

		txtfieldcontato.setBackground(java.awt.Color.darkGray);
		txtfieldcontato.setForeground(new java.awt.Color(255, 255, 255));

		jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/StudioIlma.png"))); // NOI18N
		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
		jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane1).addComponent(jSeparator2).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE).addComponent(txtfieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel3).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup().addComponent(jLabel4).addGap(3, 3, 3))).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(txtfieldcontato, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE).addComponent(txtfieldendereco)))).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)).addGroup(jPanel2Layout.createSequentialGroup().addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jLabel7).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(txtfieldservico, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE).addComponent(txtfieldvalor).addComponent(txtfielddesconto)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel9).addComponent(jLabel8).addComponent(jLabel10))).addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE).addComponent(jLabel12))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(txtfieldhora).addComponent(txtfielddia).addComponent(txtfieldfinal).addComponent(txtfieldid)))).addContainerGap()).addGroup(jPanel2Layout.createSequentialGroup().addGap(38, 38, 38).addComponent(jLabel20).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(btnatualizar).addGap(18, 18, 18).addComponent(jButton4).addGap(80, 80, 80)).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel1).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE).addGroup(jPanel2Layout.createSequentialGroup().addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel16).addComponent(jLabel15).addComponent(jLabel19))).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup().addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel18)).addGroup(jPanel2Layout.createSequentialGroup().addGap(12, 12, 12).addComponent(jLabel14)).addGroup(jPanel2Layout.createSequentialGroup().addGap(161, 161, 161).addComponent(jLabel13)))).addGroup(jPanel2Layout.createSequentialGroup().addGap(29, 29, 29).addComponent(jLabel17))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE).addComponent(jLabel21).addGap(28, 28, 28)))));
		jPanel2Layout.setVerticalGroup(
		jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addGap(30, 30, 30).addComponent(jLabel1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addGap(18, 18, 18).addComponent(jLabel13).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jLabel14).addGap(18, 18, 18).addComponent(jLabel15).addGap(18, 18, 18).addComponent(jLabel16).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel17).addGap(18, 18, 18).addComponent(jLabel18).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 38, Short.MAX_VALUE)).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE).addGap(18, 18, 18))).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(btnatualizar).addComponent(jButton4)).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup().addComponent(jLabel19).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel20))).addGap(18, 18, 18))).addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(txtfieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel5).addComponent(txtfieldservico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel8).addComponent(txtfielddia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel2)).addGap(18, 18, 18).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel6).addComponent(txtfieldvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel9).addComponent(txtfieldhora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(txtfieldcontato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel3)).addGap(18, 18, 18).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4).addComponent(txtfieldendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel7).addComponent(txtfielddesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(txtfieldid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel10))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel12).addComponent(txtfieldfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(15, 15, 15)).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup().addComponent(jLabel11).addContainerGap()))));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
		jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(
		jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
		layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap().addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addContainerGap()));
		layout.setVerticalGroup(
		layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addContainerGap()));

		pack();
	} // </editor-fold>//GEN-END:initComponents
	private void txtfieldservicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfieldservicoMouseClicked
		// TODO add your handling code here:
		//Criando um JComboBox com o serviços e setando o valor do mesmo na tabela.
		int linhaSelecionada = tabelaservicos.getSelectedRow();

		DefaultTableModel model = (DefaultTableModel) tabelaservicos.getModel();

		try {

			String[] servs = {
				"Mechas",
				"Progressiva",
				"Corte",
				"Escova",
				"Hidratação",
				"Cauterização",
				"Reconstrução Capilar",
				"Penteado",
				"Maquiagem",
				"Luzes",
				"Balayage"
			};

			JComboBox jcb = new JComboBox(servs);

			JOptionPane.showMessageDialog(null, jcb, "Selecione o novo Serviço: ", JOptionPane.QUESTION_MESSAGE);
			model.setValueAt(jcb.getSelectedItem(), linhaSelecionada, 4);

			txtfieldservico.setText(model.getValueAt(linhaSelecionada, 4).toString());

		} catch(ArrayIndexOutOfBoundsException arr) {
			JOptionPane.showMessageDialog(null, "Selecione um serviço na tabela antes de atualizar o serviço!", "Atualizar", JOptionPane.ERROR_MESSAGE);
		}
	}//GEN-LAST:event_txtfieldservicoMouseClicked
	private void btnatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatualizarActionPerformed
		// TODO add your handling code here:
		JPasswordField password = new JPasswordField(15);

		JLabel rotulo = new JLabel("Insira sua senha: ");
		JPanel entUsuario = new JPanel();
		entUsuario.add(rotulo);
		entUsuario.add(password);

		JOptionPane.showMessageDialog(null, entUsuario, "Acesso restrito", JOptionPane.PLAIN_MESSAGE);

		String senha = password.getText();

		if (senha.equals("fran123")) {
			cadastrarValores();
			ordenarTabela();
			limparCampos();
			exportarDados();

			//Opcional, apenas para os dados ficarem visiveis na jtable da tela de atualizar
			DefaultTableModel model = (DefaultTableModel) tabelaservicos.getModel();

			int rows = model.getRowCount();

			for (int i = rows - 1; i >= 0; i--) {
				model.removeRow(i);
			}

			importarDados();

		} else {
			JOptionPane.showMessageDialog(null, "Senha incorreta, tente novamente!", "ERRO!", JOptionPane.ERROR_MESSAGE);
		}

	}//GEN-LAST:event_btnatualizarActionPerformed
	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
		// TODO add your handling code here:
		this.dispose();
	}//GEN-LAST:event_jButton4ActionPerformed
	private void tabelaservicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaservicosMouseClicked
		// TODO add your handling code here:
		// get the selected row index
		int linhaSelecionada = tabelaservicos.getSelectedRow();

		// get the model from the jtable
		DefaultTableModel model = (DefaultTableModel) tabelaservicos.getModel();

		// set the selected row data into jtextfields
		txtfieldnome.setText(model.getValueAt(linhaSelecionada, 1).toString());
		txtfieldcontato.setText(model.getValueAt(linhaSelecionada, 2).toString());
		txtfieldendereco.setText(model.getValueAt(linhaSelecionada, 3).toString());
		txtfieldservico.setText(model.getValueAt(linhaSelecionada, 4).toString());
		txtfieldvalor.setText(model.getValueAt(linhaSelecionada, 5).toString());
		txtfielddesconto.setText(model.getValueAt(linhaSelecionada, 6).toString());
		txtfielddia.setText(model.getValueAt(linhaSelecionada, 7).toString());
		txtfieldhora.setText(model.getValueAt(linhaSelecionada, 8).toString());
		txtfieldid.setText(model.getValueAt(linhaSelecionada, 0).toString());
		txtfieldfinal.setText(model.getValueAt(linhaSelecionada, 9).toString());
	}//GEN-LAST:event_tabelaservicosMouseClicked
	/**
     * @param args the command line arguments
     */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info: javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch(ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaAtualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch(InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaAtualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch(IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaAtualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch(javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaAtualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				TelaAtualizar dialog = new TelaAtualizar(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnatualizar;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JTable tabelaservicos;
	private javax.swing.JTextField txtfieldcontato;
	private javax.swing.JTextField txtfielddesconto;
	private javax.swing.JTextField txtfielddia;
	private javax.swing.JTextField txtfieldendereco;
	private javax.swing.JTextField txtfieldfinal;
	private javax.swing.JTextField txtfieldhora;
	private javax.swing.JTextField txtfieldid;
	private javax.swing.JTextField txtfieldnome;
	private javax.swing.JTextField txtfieldservico;
	private javax.swing.JTextField txtfieldvalor;
	// End of variables declaration//GEN-END:variables
}